{{- if and (not .Values.existingSecret) (not .Values.secrets.create) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tg-monitor-bot.fullname" . }}-env
  labels:
    {{- include "tg-monitor-bot.labels" . | nindent 4 }}
  annotations:
    # Keep secret on helm upgrade/reinstall to prevent regenerating API key
    helm.sh/resource-policy: keep
type: Opaque
stringData:
  {{- range $key, $value := .Values.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
{{- if .Values.secrets.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tg-monitor-bot.fullname" . }}
  labels:
    {{- include "tg-monitor-bot.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.secrets.TELEGRAM_TOKEN }}
  TELEGRAM_TOKEN: {{ .Values.secrets.TELEGRAM_TOKEN | quote }}
  {{- end }}
  {{- if .Values.secrets.API_KEY }}
  API_KEY: {{ .Values.secrets.API_KEY | quote }}
  {{- end }}
{{- end }}
